### ISSUE TITLE
Layout keymaps don't work

### ISSUE THREAD

**Issue by dsandstrom** [leny/atom-pane-manager#2]
The keymaps like `cmd-k cmd-l cmd-2` don't work.  You have several `'.platform-darwin atom-workspace'` blocks in you keymap file, so only the last one is getting used.  Likewise for linux/win32.  Combine them into one for each OS and they will work (put all layout/move/focus keymaps under one `.platform-darwin atom-workspace'`).

**Comment by leny** [comment]
Hi, thanks for the report.

It's fixed and published as `v0.1.5`.
